//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShreeGroup.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class APIDetails
    {
        public int Id { get; set; }
        public string RazorKey { get; set; }
        public string RazorSecret { get; set; }
        public string SMSKey { get; set; }
        public string SMSSecret { get; set; }
        public string SMSMessage { get; set; }
        public int Amount { get; set; }
        public Nullable<int> APINumber { get; set; }
    }
}
