//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShreeGroup.DAL.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string MiddleName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string PinCode { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string DateOfBirth { get; set; }
        public Nullable<int> Age { get; set; }
        public string ProfilePicture { get; set; }
        public Nullable<bool> isVaccinated { get; set; }
        public string AadharCard { get; set; }
        public string QRCode { get; set; }
        public string RegistrationCode { get; set; }
        public Nullable<int> UrlId { get; set; }
        public string UrlCode { get; set; }
        public string District { get; set; }
        public string AadharCardImage { get; set; }
        public string BloodGroup { get; set; }
        public string TransactionId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<bool> IsPaymentDone { get; set; }
    }
}
