//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShreeGroup.DAL.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ShreeGroupUmrethEntities : DbContext
    {
        public ShreeGroupUmrethEntities()
            : base("name=ShreeGroupUmrethEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<APIDetails> APIDetails { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<GeneralSeatBooking> GeneralSeatBooking { get; set; }
    }
}
